//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectTesis.Service.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Fac_Ventas
    {
        public int Cliente_Key { get; set; }
        public int Empleado_Key { get; set; }
        public int Producto_Key { get; set; }
        public int Tiempo_Key { get; set; }
        public decimal Precio { get; set; }
        public int Cantidad { get; set; }
        public decimal Monto { get; set; }
        public decimal RecargoUsoTarjeta { get; set; }
        public decimal MontoTotal { get; set; }
    
        public virtual Dim_Cliente Dim_Cliente { get; set; }
        public virtual Dim_Empleado Dim_Empleado { get; set; }
        public virtual Dim_Producto Dim_Producto { get; set; }
        public virtual Dim_Tiempo Dim_Tiempo { get; set; }
    }
}
